name: linux 64 bit build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps: 
      - name: get code
      - uses: actions/checkout@v4
#      - name: install dependencies
#      - run: |
#          apt install wireguard-tools libgtk-3-dev libayatana-appindicator3-dev golang-go
      
    
