name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install build dependencies
        run: |
          sudo apt update
          ./deps.sh

      - name: Install dependencies
        run: go mod download

      - name: Build deb
        run: ./package_deb.sh

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$GITHUB_REF_NAME" --notes "Release $GITHUB_REF_NAME" ./build/*.deb
